#!/bin/bash


SRCS="src/control.c src/debug.c src/model-vbar.c src/pyt-cu-plug-alloc.c"
docker build -t manylinux-cuda -f docker/cuda-on-manylinux.Dockerfile .
docker run --rm -v $(pwd):/project -w /project manylinux-cuda \
    gcc -shared -o comfy_aimdo/aimdo.so -fPIC -Werror \
    -I/usr/local/cuda/include \
    -L/usr/local/cuda-12.1/targets/x86_64-linux/lib/stubs/  \
    ${SRCS} -lcuda
